version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    commit-message:
      prefix: "TCS-3"
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - "minor"
          - "patch"
