image: node:22.9-bookworm
options:
  max-time: 10
definitions:
  caches:
    pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store
pipelines:
  pull-requests:
    "**":
      - step:
          name: Test
          script:
            - corepack enable
            - corepack prepare pnpm@latest-9 --activate
            - pnpm install
            - pnpm test
          caches:
            - pnpm
